import type { ConceptualProblem } from "@/lib/problems/types";

export const whyEnergyIsConserved: ConceptualProblem = {
  meta: {
    slug: "why-energy-is-conserved",
    title: "Why ⟨H⟩ Is Conserved for Any State",
    course: "classical-to-quantum",
    lesson: "quantum-mechanics/classical-to-quantum/stationary-states",
    difficulty: "intermediate",
    estimatedMinutes: 6,
    problemType: "conceptual",
    tags: ["stationary-states", "conservation"],
    prerequisites: ["quantum-mechanics/classical-to-quantum/stationary-states"],
  },
  question: {
    type: "conceptual",
    prompt:
      "Explain why ⟨H⟩ is exactly conserved for every state evolving under H, not only for energy eigenstates.",
    placeholder: "Explain using U(t) and H...",
  },
  answer: {
    type: "conceptual",
    requiredConceptGroups: [
      {
        phrases: ["commutes with h", "built from h", "function of h", "u(t) is built entirely"],
        missingFeedback:
          "Look at what the evolution operator is actually made of. Say what its relationship to H is, and why that relationship is automatic.",
      },
      {
        // The ASCII spellings matter as much as the glyph one. A student
        // typing into a plain text box writes "U-dagger H U" or "U^dagger H
        // U", never "†", so spelling the key step only as `u†hu = h` marked
        // down answers that had genuinely done the algebra. None of the added
        // phrases can be echoed from the prompt, which contains no "dagger"
        // token and no "u" at all.
        phrases: [
          "u†hu = h",
          "u dagger h u",
          "u^dagger h u",
          "u-dagger h u",
          "unchanged",
          "conserved",
          "stays the same",
          "comes out the same",
          "same at every time",
          "doesn't depend on t",
        ],
        missingFeedback:
          "You have the relationship. Now push it through the expectation value: say what the sandwiched Hamiltonian comes to, and what that leaves the expectation doing over time.",
      },
    ],
    incorrectFeedback:
      "You argued from energy eigenstates, which is the special case the question excludes. Nothing about the state should enter: look at what the evolution operator is made of, and then evaluate the sandwich U†(t) H U(t) for an arbitrary state.",
    partialFeedback: "You have one step. Add the other: show what the two evolution operators do to the H sitting between them, and then what is left of the sandwich.",
    modelAnswers: [
      "The evolution operator is built entirely out of H, so it commutes with H. That makes U-dagger H U equal to H, and the expectation value comes out unchanged at every time, for any state at all and not just eigenstates.",
      "Because the evolution operator is a function of H, it commutes with H, so H is left the same under the transformation and its expectation value stays the same as time goes on.",
    ],
  },
  hints: [
    { text: "Look at what the evolution operator is made of. Write out its series expansion and note what every term contains." },
    { text: "An operator whose every term is a power of H has an obvious relationship with H. State it." },
    { text: "Use that relationship to move one of the two evolution operators past the H in ⟨ψ(t)|H|ψ(t)⟩, and then simplify what the pair leaves behind." },
  ],
  solution: {
    steps: [
      { description: "$U(t)=e^{-iHt/\\hbar}$ is a power series in $H$ alone, so it commutes with $H$: $U(t)H=HU(t)$." },
      { description: "Then $U^\\dagger(t)HU(t)=H$ exactly." },
      { description: "$\\langle H\\rangle_t = \\langle\\psi(0)|U^\\dagger(t)HU(t)|\\psi(0)\\rangle = \\langle\\psi(0)|H|\\psi(0)\\rangle = \\langle H\\rangle_0$, independent of $t$." },
    ],
    finalAnswer: "⟨H⟩ is conserved because U(t) is built purely from H and therefore commutes with it.",
  },
  explanation: {
    correctIdea: "Conservation of energy is a structural consequence of the evolution operator being generated by H itself.",
    whyCorrect: "This argument works for any initial state, not only eigenstates, which makes it the stronger statement.",
    whyWrong: ["Restricting the argument to eigenstates only (i.e., 'because it starts as a definite energy') misses that the derivation never assumed the initial state was an eigenstate at all."],
  },
};
