import type { ConceptualProblem } from "@/lib/problems/types";

export const whyEnergyIsConserved: ConceptualProblem = {
  meta: {
    slug: "why-energy-is-conserved",
    title: "Why ⟨H⟩ Is Conserved for Any State",
    course: "classical-to-quantum",
    lesson: "quantum-mechanics/classical-to-quantum/stationary-states",
    difficulty: "intermediate",
    estimatedMinutes: 6,
    problemType: "conceptual",
    tags: ["stationary-states", "conservation"],
    prerequisites: ["quantum-mechanics/classical-to-quantum/stationary-states"],
  },
  question: {
    type: "conceptual",
    prompt:
      "Explain why ⟨H⟩ is exactly conserved for every state evolving under H, not only for energy eigenstates.",
    placeholder: "Explain using U(t) and H...",
  },
  answer: {
    type: "conceptual",
    requiredConceptGroups: [
      ["commutes with h", "built from h", "function of h", "u(t) is built entirely"],
      ["u†hu = h", "unchanged", "conserved", "stays the same", "doesn't depend on t"],
    ],
    incorrectFeedback:
      "Think about what U(t)=e^{-iHt/ℏ} is built out of, and what that implies for U†(t)HU(t).",
    partialFeedback: "You're partway there — connect U(t) commuting with H to the sandwich ⟨ψ(t)|H|ψ(t)⟩ staying fixed.",
  },
  hints: [
    { text: "U(t) is a power series built entirely out of H." },
    { text: "Anything built purely from H commutes with H." },
    { text: "If U(t) commutes with H, what does U†(t)HU(t) simplify to?" },
  ],
  solution: {
    steps: [
      { description: "$U(t)=e^{-iHt/\\hbar}$ is a power series in $H$ alone, so it commutes with $H$: $U(t)H=HU(t)$." },
      { description: "Then $U^\\dagger(t)HU(t)=H$ exactly." },
      { description: "$\\langle H\\rangle_t = \\langle\\psi(0)|U^\\dagger(t)HU(t)|\\psi(0)\\rangle = \\langle\\psi(0)|H|\\psi(0)\\rangle = \\langle H\\rangle_0$, independent of $t$." },
    ],
    finalAnswer: "⟨H⟩ is conserved because U(t) is built purely from H and therefore commutes with it.",
  },
  explanation: {
    correctIdea: "Conservation of energy is a structural consequence of the evolution operator being generated by H itself.",
    whyCorrect: "This argument works for any initial state, not only eigenstates — a stronger, more general statement.",
    whyWrong: ["Restricting the argument to eigenstates only (i.e., 'because it starts as a definite energy') misses that the derivation never assumed the initial state was an eigenstate at all."],
  },
};
