import type { ConceptualProblem } from "@/lib/problems/types";

export const whyP1UsesHalfAngle: ConceptualProblem = {
  meta: {
    slug: "why-p1-uses-half-angle",
    title: "Why P₁(t)=sin²(θ/2), Not sin²(θ)",
    course: "control-and-readout",
    lesson: "quantum-hardware/control-and-readout/control-electronics",
    difficulty: "advanced",
    estimatedMinutes: 6,
    problemType: "conceptual",
    tags: ["control-electronics", "conceptual"],
    prerequisites: ["quantum-hardware/control-and-readout/control-electronics"],
  },
  question: {
    type: "conceptual",
    prompt: "Explain why the measured population P₁(t)=sin²(θ/2) uses HALF the rotation angle θ, rather than θ itself, connecting to the general fact that a rotation by θ on the Bloch sphere corresponds to Ωt=θ/2.",
    placeholder: "A rotation by angle θ on the Bloch sphere corresponds to a Hamiltonian phase of...",
  },
  answer: {
    type: "conceptual",
    requiredConceptGroups: [
      ["bloch sphere", "half-angle", "spin-1/2", "rotation operator"],
      ["Ωt = θ/2", "phase", "generator"],
    ],
    incorrectFeedback: "Connect this to the general spin-1/2 rotation-operator half-angle convention, not just restate the formula.",
    partialFeedback: "Good — now be explicit that this is the same half-angle structure appearing throughout spin-1/2 physics, not something specific to this control-electronics context.",
  },
  hints: [
    { text: "This is the same half-angle structure Angular Momentum & Spin's rotation operators use: a Bloch-sphere rotation by θ corresponds to a Hamiltonian evolution phase of θ/2." },
    { text: "The two-level Rabi Hamiltonian generates exactly this kind of rotation." },
    { text: "So the Rabi phase Ωt equals θ/2, not θ, for a target Bloch-sphere rotation angle θ." },
  ],
  solution: {
    steps: [
      { description: "A rotation by angle θ on the Bloch sphere is generated by a spin-1/2 rotation operator, which carries the well-known half-angle structure (e.g. e^{-iθσ/2}) throughout spin-1/2 physics — this is not specific to control electronics, but a general feature already seen in Angular Momentum & Spin." },
      { description: "The resonant-drive Hamiltonian generates exactly this kind of rotation, so the accumulated Rabi phase Ωt equals θ/2, not θ, for a target rotation angle θ." },
      { description: "Substituting into P₁(t)=sin²(Ωt) then gives P₁(t)=sin²(θ/2) directly." },
    ],
    finalAnswer: "The half-angle comes from spin-1/2's rotation-operator convention (a general fact, not specific to control electronics): a Bloch-sphere rotation by θ requires Ωt=θ/2, giving P₁=sin²(θ/2).",
  },
  explanation: {
    correctIdea: "This connects a control-engineering formula back to a deeper, already-established piece of physics (spin-1/2's half-angle rotation convention), rather than treating it as an arbitrary factor of 2 to memorize.",
    whyCorrect: "Matches the general spin-1/2 rotation structure used throughout this platform's Angular Momentum & Spin course.",
    whyWrong: ["Treating the factor of 2 as an unexplained empirical constant, rather than connecting it to the half-angle rotation-operator structure, misses the deeper reason."],
  },
};
