import type { ConceptualProblem } from "@/lib/problems/types";

export const whyP1UsesHalfAngle: ConceptualProblem = {
  meta: {
    slug: "why-p1-uses-half-angle",
    title: "Why P₁(t)=sin²(θ/2), Not sin²(θ)",
    course: "control-and-readout",
    lesson: "quantum-hardware/control-and-readout/control-electronics",
    difficulty: "advanced",
    estimatedMinutes: 6,
    problemType: "conceptual",
    tags: ["control-electronics", "conceptual"],
    prerequisites: ["quantum-hardware/control-and-readout/control-electronics"],
  },
  question: {
    type: "conceptual",
    prompt: "Explain why the measured population P₁(t)=sin²(θ/2) uses half the rotation angle θ rather than θ itself, connecting to the general fact that a rotation by θ on the Bloch sphere corresponds to Ωt=θ/2.",
    placeholder: "A rotation by angle θ on the Bloch sphere corresponds to a Hamiltonian phase of...",
  },
  answer: {
    type: "conceptual",
    requiredConceptGroups: [
      {
        phrases: ["spin-1/2", "rotation operator", "rotation convention", "spin one half", "su(2)"],
        missingFeedback:
          "The factor of two is not an artefact of the control hardware. Name the piece of physics it comes from, the one that governs how turns on the Bloch sphere act on a two-level system.",
      },
      {
        phrases: ["half the angle", "half of the angle", "theta over two", "rabi phase", "accumulated phase", "generator"],
        missingFeedback:
          "You have named where the convention comes from. Now state it as a relation: say what the phase built up during the drive equals, in terms of the Bloch-sphere angle.",
      },
    ],
    incorrectFeedback: "Restating P₁=sin²(θ/2) is not an explanation of where the 2 comes from. The factor is not a property of control electronics at all; it is the same convention that appears every time a two-level system is turned on the sphere, and it was established well before this lesson. Say which convention that is, and connect Ωt to θ through it.",
    partialFeedback: "Good. Now say explicitly that this is a general fact about turning a two-level system, established long before any control hardware appeared, rather than a quirk of how a Rabi drive is engineered.",
    modelAnswers: [
      "The factor of two comes from the spin-1/2 rotation operator convention, not from the electronics. A Bloch sphere rotation by theta is generated by something carrying half the angle, so the Rabi phase has to equal theta over two, and the population comes out as sin^2 of that.",
      "In SU(2) a rotation by theta on the Bloch sphere corresponds to an accumulated phase of theta/2 in the state itself. So the measured population is sin^2(theta/2): it is the rotation convention for spin one half, a general fact rather than an arbitrary factor.",
    ],
  },
  hints: [
    { text: "Angular Momentum & Spin already fixed a convention for turning a two-level system: a turn by θ on the sphere corresponds to an evolution by θ/2 in the exponent." },
    { text: "The two-level Rabi Hamiltonian generates exactly this kind of rotation." },
    { text: "So Ωt is not θ. Work out what it is instead, for a target rotation angle θ." },
  ],
  solution: {
    steps: [
      { description: "A rotation by angle θ on the Bloch sphere is generated by a spin-1/2 rotation operator, which carries the familiar half-angle structure e^{-iθσ/2} throughout spin-1/2 physics. This is not specific to control electronics; it is a general feature already seen in Angular Momentum & Spin." },
      { description: "The resonant-drive Hamiltonian generates exactly this kind of rotation, so the accumulated Rabi phase Ωt equals θ/2, not θ, for a target rotation angle θ." },
      { description: "Substituting into P₁(t)=sin²(Ωt) then gives P₁(t)=sin²(θ/2) directly." },
    ],
    finalAnswer: "The half-angle comes from spin-1/2's rotation-operator convention, a general fact rather than something specific to control electronics: a Bloch-sphere rotation by θ requires the Rabi phase Ωt to equal half the angle, θ/2, giving P₁=sin²(θ/2).",
  },
  explanation: {
    correctIdea: "This connects a control-engineering formula back to a deeper, already-established piece of physics (spin-1/2's half-angle rotation convention), rather than treating it as an arbitrary factor of 2 to memorize.",
    whyCorrect: "A rotation by θ on the Bloch sphere is generated by e^{-iθσ/2}, so the phase the drive accumulates is θ/2 rather than θ. The factor is inherited from the way SU(2) covers SO(3), which is why it turns up identically in Angular Momentum & Spin and has nothing to do with the electronics.",
    whyWrong: ["Treating the factor of 2 as an unexplained empirical constant, rather than connecting it to the half-angle rotation-operator structure, misses the deeper reason."],
  },
};
