import type { ConceptualProblem } from "@/lib/problems/types";

export const whyNormIsPreserved: ConceptualProblem = {
  meta: {
    slug: "why-norm-is-preserved",
    title: "Why Time Evolution Preserves Normalization",
    course: "wave-mechanics",
    lesson: "quantum-mechanics/wave-mechanics/probability-density-and-normalization",
    difficulty: "intermediate",
    estimatedMinutes: 6,
    problemType: "conceptual",
    tags: ["normalization", "unitarity", "time-evolution"],
    prerequisites: ["quantum-mechanics/wave-mechanics/probability-density-and-normalization"],
  },
  question: {
    type: "conceptual",
    prompt:
      "In one or two sentences, explain why a normalized wavefunction stays exactly normalized under Schrodinger time evolution, using the property U^dagger*U = I.",
    placeholder: "Explain the unitarity argument for norm preservation...",
  },
  answer: {
    type: "conceptual",
    requiredConceptGroups: [
      ["unitary", "U dagger U", "U^dagger U = I"],
      ["inner product preserved", "norm preserved", "exactly", "not approximately"],
    ],
    incorrectFeedback: "Name both pieces: that time evolution is generated by a unitary operator U with U-dagger U = I, and that this exactly preserves the inner product (hence the norm).",
    partialFeedback: "You're partway there — connect U-dagger U = I explicitly to why the norm can't drift.",
  },
  hints: [
    { text: "Write out <psi(t)|psi(t)> using |psi(t)> = U(t)|psi(0)>." },
    { text: "What does U^dagger U = I let you simplify that expression to?" },
  ],
  solution: {
    steps: [
      { description: "$\\langle\\psi(t)|\\psi(t)\\rangle = \\langle\\psi(0)|U^\\dagger U|\\psi(0)\\rangle = \\langle\\psi(0)|\\psi(0)\\rangle$, using $U^\\dagger U=I$." },
      { description: "So the norm at time $t$ exactly equals the norm at $t=0$, for every $t$." },
    ],
    finalAnswer: "Because U is unitary (U-dagger U = I), the inner product <psi(t)|psi(t)> equals <psi(0)|psi(0)> exactly, for all t.",
  },
  explanation: {
    correctIdea: "Unitary evolution exactly preserves inner products, which is exactly what norm preservation requires.",
    whyCorrect: "This is a direct algebraic identity, not an approximation — it holds for every t, not just on average.",
    whyWrong: ["Saying norm is preserved 'because probability must be conserved' restates the conclusion rather than explaining the mechanism — the actual mechanism is the algebraic property U^dagger U=I."],
  },
};
